### ISSUE TITLE
Code blocks have strange markup inside them

### ISSUE THREAD

**Issue by adam12** [unpoly/unpoly-site#21]
<img width="856" alt="image" src="https://github.com/unpoly/unpoly-site/assets/17083/e8d49023-07d9-4ce9-9c07-29ad59a8885d">

https://unpoly.com/up-validate

**Comment by adam12** [comment]
Nice! I was going to try to find time to look into this.

**Comment by triskweline** [comment]
I learnt a lot of things I never wanted to know about XPath :smile:
