### ISSUE TITLE
Ubuntu Mono should be loaded from HTTPS URL

### ISSUE THREAD

**Issue by rik** [unpoly/unpoly-site#25]
The ["story"](https://triskweline.de/unpoly-rugb/#/33) linked from the homepage is falling back to the serif font because Ubuntu Mono is not loading. Here's the error message:

```
[Warning] [blocked] The page at https://triskweline.de/unpoly-rugb/#/ requested
insecure content from http://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700.
This content was blocked and must be served over HTTPS.
```

On top of fixing the linked URL, changing `.reveal code` to `font-family: Ubuntu Mono, monospace;` would be helpful. It would have made this issue less visible but it can also benefit people that will block either custom fonts or google domains.

Note: I know this isn't part of unpoly-site but that's the closest place I could find to give feedback.

**Comment by triskweline** [comment]
Thanks for letting me know. I changed the link to use HTTPS.

> Note: I know this isn't part of unpoly-site but that's the closest place I could find to give feedback.

I just realized this was still in a private repo from way back then. I published it to https://github.com/unpoly/unpoly-story-slides .
